### ISSUE TITLE
Write None problem while uploading OpenWRT netgear r7000

### ISSUE THREAD

**Issue by YuanGao19** [cyruscyliu/firmguide#2]
While I'm running the command `./firmguide upload -f examples/routers/openwrt-15.05.1-bcm53xx-netgear-r7000-squashfs.chk`, I received output as follows and the program stopped.  Is that a normal result? 

According to the FirmGuide paper's result (Table 5), all of the bcm53xx/generic firmwares downloaded from https://archive.openwrt.org/chaos_calmer/15.05.1/bcm53xx/generic/ should be able to reach the shell. So I'm quite confused by this situation. Did you collect the firmwares from the archive.openwrt website I mentioned above?
`
2023-05-17 22:34:40,356 - INFO - AnalysesManager - chain cont'd - bfilter(invalid)->msearch(invalid)->unpack->preprocdt->synthesisdt
2023-05-17 22:34:40,356 - INFO - AnalysesManager - chain cont'd - install->loaddr(invalid)->preparation->tracing->loadtrace
2023-05-17 22:34:40,356 - INFO - AnalysesManager - chain cont'd - userlevel(invalid)->fastuserlevel->deltrace

WARNING: Extractor.execute failed to run external extractor 'ubireader_extract_files -o '%%ubifs-root%%' '%e'': [Errno 2] No such file or directory: 'ubireader_extract_files'
2023-05-17 22:35:32,466 - INFO - Unpack - unpack - find /home/yuan-gao19/Desktop/firmguide/_openwrt-15.05.1-bcm53xx-netgear-r7000-squashfs.chk.extracted/_56.kernel.extracted/153120.dtb
2023-05-17 22:35:32,468 - INFO - DTPreprocessing - preprocdt - dtb at /home/yuan-gao19/Desktop/firmguide/_openwrt-15.05.1-bcm53xx-netgear-r7000-squashfs.chk.extracted/_56.kernel.extracted/153120.dtb
2023-05-17 22:35:32,468 - INFO - DTPreprocessing - preprocdt - dts at /home/yuan-gao19/Desktop/firmguide/153120.dtb.dts
2023-05-17 22:35:32,468 - INFO - DTPreprocessing - preprocdt - board id 0xFFFFFFFF is chosen automatically
2023-05-17 22:35:32,481 - INFO - DTPreprocessing - preprocdt - arch arm is chosen automatically
2023-05-17 22:35:32,481 - INFO - DTPreprocessing - preprocdt - endian l is chosen automatically
2023-05-17 22:35:32,481 - INFO - DTPreprocessing - preprocdt - load address 0x00008000 is chosen automatically
2023-05-17 22:35:33,134 - INFO - SynthesisDT - synthesisdt - save at /home/yuan-gao19/Desktop/firmguide/fg_netgear_r7000_brcm_bcm4709_brcm_bcm4708/hw/arm/fg_netgear_r7000_brcm_bcm4709_brcm_bcm4708.c
Traceback (most recent call last):
  File "./firmguide.py", line 110, in <module>
    analysis_manager.run()
  File "/home/yuan-gao19/Desktop/firmguide/slcore/amanager.py", line 153, in run
    res = a.run(**self.arguments)
  File "/home/yuan-gao19/Desktop/firmguide/slcore/analyses/synthsisdt.py", line 260, in run
    self.__save(v['source'], base, location, fname)
  File "/home/yuan-gao19/Desktop/firmguide/slcore/analyses/synthsisdt.py", line 301, in __save
    f.write(s)
TypeError: write() argument must be str, not None
`

**Comment by YuanGao19** [comment]
Also, I beg your pardon, is the KLEE symbolic execution part included in this project? I just can't find the symbolic execution code.

**Comment by cyruscyliu** [comment]
For the first question, it seems two files are missing. I guess I forgot the add and commit them. They should be on the server where I ran the large-scale evaluation. I have contacted my colleague to get me access to that server again. 

For the second question, yes, not available anymore. I should mention it somewhere. I will do it later.

For the third question, not in this repo.

**Comment by cyruscyliu** [comment]
For the first question, it seems two files are missing. I guess I forgot the add and commit them. They should be on the server where I ran the large-scale evaluation. I have contacted my colleague to get me access to that server again. 

For the second question, yes, not available anymore. I should mention it somewhere. I will do it later.

For the third question, not in this repo.

**Comment by cyruscyliu** [comment]
I fixed the dependency issues and added the missing files. I can boot the kernel openwrt-15.05.1-bcm53xx-netgear-r7000-squashfs.chk on my machine.

**Comment by cyruscyliu** [comment]
I also redirect the firmguide-demo to https://github.com/cyruscyliu/firmguide/tree/master/examples/demo.

Thank you for your kind reminder.

**Comment by cyruscyliu** [comment]
Please close the issue if you can boot the kernel on your side.
